# -*- coding: utf-8 -*-
"""Ailab1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SaeN2s65nIgUYr7AtLmo5G2BL-bsGMbk
"""

a=5;
b=4;
sum=a+b;
print(sum)
div=a/b
print(div)
prod=a*b
print(prod)
sub=a-b
print(sub)

"""Muhammad ilyas
Sp23-bcs-107
A

*   **addition**
*  **subtraction**


*   multiplication
*  Division




"""