# -*- coding: utf-8 -*-
"""LabAI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1234gxcfl85vtbjrqBwZXvgdbYPUoL6m6

**MatplotLib:**

**Numpy:**

**LIST:**
"""

from re import L
LIST=[1,2,3,4,5,6,7,8,9,10]
print(LIST)
print ('sum',sum(LIST))
print ('max',max(LIST))
print ('min',min(LIST))
LIST.append (11)
LIST.remove(2)
print(LIST)

"""**Tuple**"""

fruits =('apple','mango','grape')
print('secomd element',fruits[1])
print('last element',fruits[-1])
print('Original tuple:', fruits)

fruits_list=list(fruits)
fruits_list[2] ='orange'
print('Modified list:',fruits_list)

"""**Set**"""

set_odd={1,3,5,7}
set_even={2,4,6,8}
set_odd.add(9)
set_odd.remove(7)
print('union:',set_odd | set_even)
print('intersection:',set_odd & set_even)
print('Diffeance:',set_odd - set_even)

"""**Dictionery**"""

students = {'ali':85, 'ali': 80,'ali': 70}
print(students)